api:
  key: HDE3ab698f24d4211ee92a
  secret: 3ab6991d4d4211ee92a802b67259d33a

spring:
  datasource:
    username: root
    password: mysql
    url: jdbc:mysql://localhost:3306/chilibubble
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    properties:
      hibernate:
        ddl-auto: true
        format_sql: true
  sql:
    init:
      data-locations: classpath*:data.sql
      mode: always
      platform: mysql

  redis:
    host: localhost
    port: 6379

logging:
  level:
    sql: trace


jwt:
  secret:
    key: ${JWT_SECRET_KEY}